version: "3.9"

volumes:
  certs:
  conf:
  db:
  vhost:
  html:
  acme:

services:
  tsc-app:
    build:
      context: contexts/tsc
    restart: always
    volumes:
      - "${STATIC_DIR}/tsc/build:/usr/src/app/static"
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: "${HOST_TSC}"
      LETSENCRYPT_HOST: "${HOST_TSC}"
      API_DB_NAME: "${POSTGRES_DATABASE_TSC}"
      AUTH_DB_NAME: "${POSTGRES_DATABASE_TSC_AUTH}"
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_HOST: "db"
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    ports:
      - "3200:5555"
    container_name: tsc

  db:
    image: postgres:13.0-alpine
    container_name: postgres-database
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"

  adminer:
    image: adminer:4.8.1
    container_name: postgres-adminer
    restart: always
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  gen:
    image: jwilder/docker-gen:0.9.1
    container_name: nginx-proxy-gen
    depends_on:
      - nginx
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/templates:/etc/docker-gen/templates:ro
    command: -notify-sighup nginx-proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx
      - gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
      NGINX_DOCKER_GEN_CONTAINER: "nginx-proxy-gen"
      DEFAULT_EMAIL: "${SSL_EMAIL}"
