GET {{host_berta}}?resource=video
Accept: application/json

###

GET {{host_berta}}?resource=playlist
Accept: application/json

###

GET {{host_berta}}?resource=external-video
Accept: application/json

###

GET {{host_berta}}?resource=tracking
Accept: application/json

###