POST {{host_mailer}}
Content-Type: application/json

// page: "hainarbeit | looneys" | "" for testing
{
    "name": "glen coden",
    "email": "info@simonmeyer.de",
    "content": "glen was here",
    "page": "",
    "admin_password": "{{admin_password}}"
}

###
